name = "notification-system"
type = "javascript"

[[kv_namespaces]]
binding = "kv1"
id = "278ef0afd030434aa836e2691c2367d5"

[env.production]
compatibility_date = "2024-10-14"

main="functions/notisAPI.js"