name = "notification-system"
type = "javascript"

pages_build_output_dir = "build"

[[kv_namespaces]]
binding = "kv1"  # This will allow you to access the KV in your function
id = "278ef0afd030434aa836e2691c2367d5"  # Replace with your actual KV namespace ID

[env.production]
compatibility_date = "2024-10-14"