name = "notification-system"


# Specify the output directory for the Pages build
pages_build_output_dir = "./build"  # Adjust according to your project structure


kv_namespaces = [
    { binding = "kv1", id = "278ef0afd030434aa836e2691c2367d5" }
]

[[bindings]]
type = "service"
name = "llama3"  # The name you will use in your code
text = "f0M01klXEkb2nqHRL2_k-DiNXtsxp1TRyD_xWRwx"  # Your actual API key or secret