name = "notification-system"
account_id = "897015974ef4bf532df9d9ee3578416f"


# Specify the output directory for the Pages build
pages_build_output_dir = "./build"  # Adjust according to your project structure


kv_namespaces = [
    { binding = "kv1", id = "278ef0afd030434aa836e2691c2367d5" }
]