name = "notification-system"


# Specify the output directory for the Pages build
pages_build_output_dir = "./build"  # Adjust according to your project structure



[[env.production]]
kv_namespaces = [
    { binding = "kv1", id = "278ef0afd030434aa836e2691c2367d5" }
]


[[env.production.bindings]]
type = "secret_text"
name = "f0M01klXEkb2nqHRL2_k-DiNXtsxp1TRyD_xWRwx"  # The name you will use in your code